"""Workflow tests — decision matrix, human pause/resume, replay, what-if (Team B).

Scenarios come from ``test-cases/*.json`` (generated by sample-data/generate_sample_data.py)
so the fixtures the demo uses are the fixtures the tests prove.
"""

import asyncio
import copy

import pytest

from app.db.store import get_store
from app.workflows import underwriting_graph as wf
from tests.conftest import load_case

MATRIX = [
    ("clean_approval", "approved"),
    ("high_foir", "declined"),
    ("high_ltv", "declined"),
    ("income_mismatch", "referred"),
    ("identity_mismatch", "referred"),
    ("missing_document", "referred"),
    ("low_age", "declined"),
]


def _run(case: dict, profile: str | None = None) -> dict:
    run_id = wf.new_run_id()
    asyncio.run(wf.run_pipeline(run_id, copy.deepcopy(case["application"]), profile or case.get("policy_profile")))
    return wf.run_view(run_id)


@pytest.mark.parametrize("name,decision", MATRIX)
def test_decision_matrix(name, decision):
    case = load_case(name)
    view = _run(case)
    assert view["status"] == "completed"
    assert view["decision"] == decision, view["reasons"]
    codes = {r["code"] for r in view["reasons"]}
    for c in case["expected"].get("reason_codes_include", []):
        assert c in codes, (c, codes)
    for c in case["expected"].get("reason_codes_exclude", []):
        assert c not in codes
    assert [n["status"] for n in view["nodes"]] == ["ok"] * 10
    assert view["financials"]["formula_version"] == "v1"
    assert view["risk"]["model_version"] == "xgb-v1"
    assert view["policy"]["profile"] == "default" and view["policy"]["config"]["limits"]


def test_policy_profile_changes_outcome_and_is_snapshotted():
    case = load_case("low_age")
    strict = _run(case, "default")
    lenient = _run(case, case["alternate_policy"]["policy_profile"])
    assert strict["decision"] == "declined"
    assert lenient["decision"] == case["alternate_policy"]["expected_decision"]
    assert lenient["policy"]["profile"] == "aggressive"
    assert lenient["policy"]["config"]["limits"]["min_age"] == 18


def test_every_evidence_item_carries_citation():
    view = _run(load_case("clean_approval"))
    for e in view["evidence"]:
        assert {"field", "value", "confidence", "source_document", "page", "evidence"} <= set(e)
    assert any(e["source_document"] == "application_form" for e in view["evidence"])


def test_audit_trail_covers_every_node_with_versions():
    view = _run(load_case("clean_approval"))
    trace = wf.trace_view(view["run_id"])
    types = [s["event_type"] for s in trace["steps"]]
    assert types[0] == "RUN_STARTED" and types[-1] == "TRACE"
    assert "RUN_COMPLETED" in types
    traced = {s["payload"]["node"] for s in trace["steps"] if s["event_type"] == "TRACE"}
    assert traced == set(wf.NODES)
    completed = next(s for s in trace["steps"] if s["event_type"] == "RUN_COMPLETED")
    assert completed["payload"]["versions"]["policy"] == "default@1.0"
    seqs = [s["sequence"] for s in trace["steps"]]
    assert seqs == sorted(seqs) and len(set(seqs)) == len(seqs)


def test_low_confidence_pauses_and_resume_is_gated_on_db_state():
    case = load_case("low_confidence")
    run_id = wf.new_run_id()
    asyncio.run(wf.run_pipeline(run_id, copy.deepcopy(case["application"])))
    view = wf.run_view(run_id)
    assert view["status"] == "awaiting_human" and view["decision"] == "human_review"
    fields = [i["field"] for i in view["low_confidence"]]
    assert "monthly_income" in fields
    assert view["review_questions"]
    assert view["nodes"][2]["status"] == "paused" and view["nodes"][3]["status"] == "pending"
    # persisted: a fresh store sees the pause
    store = get_store()
    assert store.get_run(run_id)["status"] == "awaiting_human"
    store.close()

    # partial review keeps it paused
    partial = asyncio.run(wf.resume_run(run_id, {"reviewer": "r1", "reviews": case["resume"]["reviews"][:1]}))
    assert partial["status"] == "awaiting_human" and partial["pending_fields"]

    # full review completes with the corrected value driving the numbers
    final = asyncio.run(wf.resume_run(run_id, {"reviewer": "r1", "reviews": case["resume"]["reviews"][1:]}))
    assert final["status"] == "completed"
    view = wf.run_view(run_id)
    assert view["decision"] == case["expected_after_resume"]["decision"]
    assert view["financials"]["verified_income"] == 38900.0
    reviews = view["human_reviews"]
    assert len(reviews) == 2 and reviews[0]["action"] == "correct" and reviews[0]["original_value"] != 38900
    assert reviews[0]["reviewer"] == "r1" and reviews[0]["timestamp"] and reviews[0]["note"]
    corrected = [e for e in view["evidence"] if e["field"] == "monthly_income" and e["review_status"] == "corrected"]
    assert corrected and corrected[0]["value"] == 38900.0
    # resuming a completed run is refused
    again = asyncio.run(wf.resume_run(run_id, {"reviewer": "r1", "reviews": []}))
    assert "not awaiting_human" in again["error"]


def test_reviewer_decision_override_is_recorded():
    case = load_case("low_confidence")
    run_id = wf.new_run_id()
    asyncio.run(wf.run_pipeline(run_id, copy.deepcopy(case["application"])))
    asyncio.run(wf.resume_run(run_id, {"reviewer": "lead", "reviews": case["resume"]["reviews"],
                                       "decision_override": {"decision": "referred", "note": "second look"}}))
    view = wf.run_view(run_id)
    assert view["decision"] == "referred"
    assert view["human_override"]["from"] == "approved" and view["human_override"]["reviewer"] == "lead"
    assert any(r["code"] == "HUMAN_REVIEW_REQUIRED" for r in view["reasons"])


def test_replay_is_deterministic():
    view = _run(load_case("income_mismatch"))
    rep = asyncio.run(wf.replay_run(view["run_id"]))
    assert rep["deterministic"] is True
    assert all(d["equal"] for d in rep["diffs"])
    assert rep["replayed"]["decision"]["decision"] == "referred"


def test_what_if_changes_outcome_but_base_run_is_immutable():
    case = load_case("what_if_approval")
    view = _run(case)
    assert view["decision"] == "declined"
    before = wf.run_view(view["run_id"])
    res = asyncio.run(wf.what_if(view["run_id"], case["what_if"]))
    assert res["immutable"] is True
    assert res["base"]["decision"]["decision"] == "declined"
    assert res["scenario"]["decision"]["decision"] == case["expected_what_if"]["decision"]
    assert res["scenario"]["financials"]["foir"] < before["financials"]["foir"]
    assert res["min_change_for_approval"] is None or res["min_change_for_approval"]["decision"]["decision"] == "approved"
    after = wf.run_view(view["run_id"])
    assert after["decision"] == "declined" and after["financials"] == before["financials"]
    # minimum change search on the unmodified base
    res2 = asyncio.run(wf.what_if(view["run_id"], {"overrides": {}, "find_min_change": True}))
    assert res2["scenario"]["decision"]["decision"] == "declined"
    assert res2["min_change_for_approval"] and res2["min_change_for_approval"]["changes"]
    assert wf.run_view(view["run_id"])["decision"] == "declined"
    trace = wf.trace_view(view["run_id"])
    assert len(trace["what_ifs"]) == 2


def test_what_if_with_other_policy_profile():
    view = _run(load_case("clean_approval"))
    res = asyncio.run(wf.what_if(view["run_id"], {"overrides": {"loan_amount": 100000}, "policy_profile": "conservative"}))
    assert res["policy"]["profile"] == "conservative"
    assert res["scenario"]["decision"]["decision"] == "declined"  # LTV 0.83 > 0.70
    assert wf.run_view(view["run_id"])["policy"]["profile"] == "default"
